import { useEffect, useMemo, useRef, useState } from 'react';
import { CloudSun, ExternalLink, FolderPlus, Layers, Map as MapIcon, Plus, Radar, RefreshCw, Wind, Trash2 } from 'lucide-react';
import { asArray, dig, type AnyRecord, type FlightSummary } from '../lib/ofp';
import { loadLocal, saveLocal } from '../lib/storage';

declare global { interface Window { L?: any } }
interface BinderItem { id:string; title:string; airport:string; url:string; source:string }
interface FaaChart { id:string; airport:string; title:string; type:string; url:string; effective?:string }
interface RoutePoint { lat:number; lon:number; ident:string; altitudeFt:number; eta:string }
interface IcingPoint extends RoutePoint { tempC:number; humidity:number; cloud:number; severity:'trace'|'light'|'moderate' }

function loadLeaflet(){return new Promise<any>((resolve,reject)=>{if(window.L)return resolve(window.L);if(!document.querySelector('link[data-leaflet]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.leaflet='1';document.head.appendChild(l)}const e=document.querySelector('script[data-leaflet]')as HTMLScriptElement|null;if(e){e.addEventListener('load',()=>resolve(window.L));return}const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.dataset.leaflet='1';s.onload=()=>resolve(window.L);s.onerror=reject;document.head.appendChild(s)})}
function number(...values:any[]){for(const value of values){const n=Number(String(value??'').replace(/[^0-9.-]/g,''));if(Number.isFinite(n))return n}return 0}
function routePoints(ofp:AnyRecord|null):RoutePoint[]{return asArray<any>(dig(ofp,'navlog.fix','navlog.fixes')).map((f,index)=>({lat:number(f.pos_lat,f.latitude,f.lat),lon:number(f.pos_long,f.longitude,f.lon),ident:String(f.ident||f.name||index+1),altitudeFt:number(f.altitude_feet,f.altitude,f.alt,f.planned_altitude),eta:String(f.time_total||f.eta||'')})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&Math.abs(p.lat)<=90&&Math.abs(p.lon)<=180)}
function pressureLevel(altitudeFt:number){const levels=[{h:1000,a:360},{h:925,a:2500},{h:850,a:5000},{h:700,a:10000},{h:600,a:14000},{h:500,a:18000},{h:400,a:24000},{h:300,a:30000},{h:250,a:34000},{h:200,a:39000}];return levels.reduce((best,x)=>Math.abs(x.a-altitudeFt)<Math.abs(best.a-altitudeFt)?x:best,levels[0]).h}
async function analyzeIcing(points:RoutePoint[]):Promise<IcingPoint[]>{
  const sample=points.filter((_,i)=>i===0||i===points.length-1||i%Math.max(1,Math.floor(points.length/12))===0).slice(0,14);
  const groups=new Map<number,RoutePoint[]>();sample.forEach(p=>{const level=pressureLevel(p.altitudeFt);groups.set(level,[...(groups.get(level)||[]),p])});
  const hazards:IcingPoint[]=[];
  for(const [level,items] of groups){
    const latitude=items.map(p=>p.lat.toFixed(4)).join(',');const longitude=items.map(p=>p.lon.toFixed(4)).join(',');
    const vars=`temperature_${level}hPa,relative_humidity_${level}hPa,cloud_cover_${level}hPa`;
    try{
      const response=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&hourly=${vars}&forecast_days=2&timezone=UTC`);
      if(!response.ok)continue;const data=await response.json();const rows=Array.isArray(data)?data:[data];
      rows.forEach((row:any,index:number)=>{const p=items[index];if(!p)return;const times:string[]=row?.hourly?.time||[];let target=Date.now();const hhmm=String(p.eta||'').match(/(\d{1,2}):(\d{2})/);if(hhmm){const d=new Date();d.setUTCHours(Number(hhmm[1]),Number(hhmm[2]),0,0);if(d.getTime()<Date.now()-6*3600000)d.setUTCDate(d.getUTCDate()+1);target=d.getTime()}else if(/^\d+$/.test(String(p.eta||'')))target+=Number(p.eta)*1000;let hour=0;if(times.length)hour=times.reduce((best,t,i)=>Math.abs(new Date(t+'Z').getTime()-target)<Math.abs(new Date(times[best]+'Z').getTime()-target)?i:best,0);const temp=number(row?.hourly?.[`temperature_${level}hPa`]?.[hour]);const rh=number(row?.hourly?.[`relative_humidity_${level}hPa`]?.[hour]);const cloud=number(row?.hourly?.[`cloud_cover_${level}hPa`]?.[hour]);if(temp<=10&&temp>=-20&&(rh>=80||cloud>=65)){const severity=temp<=0&&temp>=-15&&(rh>=90||cloud>=80)?'moderate':rh>=85?'light':'trace';hazards.push({...p,tempC:temp,humidity:rh,cloud,severity})}})
    }catch{}
  }
  return hazards;
}

function RouteWeatherMap({ofp,flight,opacity,layer,aviation,icing}:{ofp:AnyRecord|null;flight:FlightSummary;opacity:number;layer:string;aviation:boolean;icing:boolean}){
  const ref=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null);const pts=useMemo(()=>routePoints(ofp),[ofp]);const[icingPoints,setIcingPoints]=useState<IcingPoint[]>([]);
  useEffect(()=>{let dead=false;if(!icing){setIcingPoints([]);return;}void analyzeIcing(pts).then(rows=>{if(!dead)setIcingPoints(rows)});return()=>{dead=true}},[icing,pts]);
  useEffect(()=>{let dead=false;void loadLeaflet().then(async L=>{if(dead||!ref.current)return;if(mapRef.current)mapRef.current.remove();const map=L.map(ref.current,{zoomControl:true,worldCopyJump:true});mapRef.current=map;const dark=L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:19,attribution:'© OpenStreetMap © CARTO'}).addTo(map);const bases={'Dark':dark,'Light':L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'})};const overlays:any={};
    if(pts.length>1){const route=L.polyline(pts.map(p=>[p.lat,p.lon]),{weight:4,opacity:.95,color:'#2ea7ff'}).addTo(map);overlays['SimBrief route']=route;pts.forEach((p,i)=>L.circleMarker([p.lat,p.lon],{radius:i===0||i===pts.length-1?6:3,weight:2,color:'#50baff',fillOpacity:1}).bindTooltip(`${p.ident}${p.altitudeFt?` · ${Math.round(p.altitudeFt).toLocaleString()} ft`:''}`).addTo(map));map.fitBounds(route.getBounds(),{padding:[30,30]})}else map.setView([39,-96],4);
    try{const rv=await fetch('https://api.rainviewer.com/public/weather-maps.json').then(r=>r.json());const frame=rv?.radar?.past?.at(-1);if(frame){const radar=L.tileLayer(`${rv.host}${frame.path}/256/{z}/{x}/{y}/2/1_1.png`,{opacity,zIndex:440,maxZoom:10});overlays['Reflectivity radar']=radar;if(layer==='radar')radar.addTo(map)}}catch{}
    const date=new Date().toISOString().slice(0,10);const gibs=(id:string,format='jpg',matrix='GoogleMapsCompatible_Level9')=>L.tileLayer(`https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/${id}/default/${date}/${matrix}/{z}/{y}/{x}.${format}`,{opacity,zIndex:410,maxZoom:9,attribution:'NASA GIBS'});
    const satellite=gibs('VIIRS_NOAA20_CorrectedReflectance_TrueColor','jpg','GoogleMapsCompatible_Level9');overlays['Satellite imagery']=satellite;if(layer==='satellite')satellite.addTo(map);
    const infrared=gibs('MODIS_Terra_Cloud_Phase_Infrared_Day','png','GoogleMapsCompatible_Level6');overlays['Infrared / temperature']=infrared;if(layer==='infrared')infrared.addTo(map);
    const cloudTemp=gibs('MODIS_Terra_Cloud_Top_Temperature_Day','png','GoogleMapsCompatible_Level6');overlays['Cloud-top temperature']=cloudTemp;if(layer==='cloudtemp')cloudTemp.addTo(map);
    const tile=import.meta.env.VITE_OPENAIP_TILE_URL;if(aviation&&tile){const a=L.tileLayer(tile,{opacity:.76,zIndex:460,attribution:'Aviation overlay'});a.addTo(map);overlays['Aviation overlay']=a}
    if(icing){icingPoints.forEach(p=>L.circleMarker([p.lat,p.lon],{radius:p.severity==='moderate'?9:7,weight:2,color:p.severity==='moderate'?'#ff6d74':'#62c8ff',fillColor:p.severity==='moderate'?'#9e2730':'#155f87',fillOpacity:.78}).bindTooltip(`<b>Potential ${p.severity} icing</b><br>${p.ident} · ${Math.round(p.altitudeFt).toLocaleString()} ft<br>${p.tempC.toFixed(0)}°C · RH ${p.humidity.toFixed(0)}% · cloud ${p.cloud.toFixed(0)}%`).addTo(map))}
    L.control.layers(bases,overlays,{collapsed:true,position:'topright'}).addTo(map)});return()=>{dead=true;if(mapRef.current){mapRef.current.remove();mapRef.current=null}}},[pts,flight.origin,flight.destination,opacity,layer,aviation,icing,icingPoints]);return <div ref={ref} className="route-radar-map"/>
}

export function ChartsPage({ofp,flight}:{ofp:AnyRecord|null;flight:FlightSummary;source?:any;setSource?:any}){
  const key=`aeroslate.chart-binder.${flight.origin}.${flight.destination}`;const[binder,setBinder]=useState<BinderItem[]>(()=>loadLocal(key,[])),[view,setView]=useState<'map'|'charts'|'binder'>('map'),[opacity,setOpacity]=useState(.58),[layer,setLayer]=useState('radar'),[aviation,setAviation]=useState(false),[icing,setIcing]=useState(true),[faaCharts,setFaaCharts]=useState<FaaChart[]>([]),[faaAirport,setFaaAirport]=useState(flight.origin),[chartBusy,setChartBusy]=useState(false),[selectedChart,setSelectedChart]=useState<FaaChart|null>(null);
  useEffect(()=>saveLocal(key,binder),[key,binder]);useEffect(()=>setFaaAirport(flight.origin),[flight.origin]);
  const loadFaa=async()=>{if(!faaAirport)return;setChartBusy(true);try{const r=await fetch(`/api/charts/faa?airport=${encodeURIComponent(faaAirport)}`);const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load FAA charts');setFaaCharts(j.charts||[]);setSelectedChart(j.charts?.find((c:FaaChart)=>c.type==='Airport diagram')||j.charts?.[0]||null)}catch{setFaaCharts([]);setSelectedChart(null)}finally{setChartBusy(false)}};
  useEffect(()=>{if(view==='charts'&&faaAirport)void loadFaa()},[view,faaAirport]);
  const chartGroups=useMemo(()=>faaCharts.reduce<Record<string,FaaChart[]>>((groups,chart)=>{(groups[chart.type]??=[]).push(chart);return groups},{}),[faaCharts]);
  return <div className="charts-suite"><div className="subnav-tabs"><button className={view==='map'?'active':''}onClick={()=>setView('map')}><Radar size={17}/>Map</button><button className={view==='charts'?'active':''}onClick={()=>setView('charts')}><MapIcon size={17}/>Charts</button><button className={view==='binder'?'active':''}onClick={()=>setView('binder')}><Layers size={17}/>Binder ({binder.length})</button></div>
  {view==='map'&&<section className="card map-card"><header><div><Radar size={18}/><h3>Route weather & aviation layers</h3></div><div className="map-control-strip weather-layer-controls"><select value={layer} onChange={e=>setLayer(e.target.value)}><option value="none">No weather</option><option value="radar">Reflectivity radar</option><option value="satellite">Satellite imagery</option><option value="infrared">Infrared temperature</option><option value="cloudtemp">Cloud-top temperature</option></select><button className={icing?'active':''}onClick={()=>setIcing(v=>!v)}><Wind size={13}/> Route icing</button><button className={aviation?'active':''}onClick={()=>setAviation(v=>!v)}><Layers size={13}/> Aviation</button><label><span>Opacity</span><input type="range" min="0.15" max="0.9" step="0.05" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label></div></header><div className="card-body map-body"><RouteWeatherMap ofp={ofp} flight={flight} opacity={opacity} layer={layer} aviation={aviation} icing={icing}/><div className="map-legend"><span><Radar size={13}/> RainViewer reflectivity</span><span><CloudSun size={13}/> NASA GIBS imagery</span><span><Wind size={13}/> Icing is a model-based screening overlay matched to planned fix altitude—not an approved forecast product.</span></div></div></section>}
  {view==='charts'&&<div className="chart-api-layout polished-chart-layout"><section className="card faa-chart-browser"><header><div><MapIcon size={18}/><h3>Terminal charts</h3></div><span className="pill good">FAA CURRENT</span></header><div className="card-body"><div className="chart-search-row"><input value={faaAirport} onChange={e=>setFaaAirport(e.target.value.toUpperCase())} placeholder="Airport ICAO"/><button className="primary" onClick={()=>void loadFaa()} disabled={chartBusy}><RefreshCw size={15}/>{chartBusy?'Loading…':'Refresh'}</button></div><div className="chart-group-list">{Object.entries(chartGroups).map(([group,charts])=><details key={group} open={group==='Airport diagram'||group==='Approach'}><summary><strong>{group}</strong><span>{charts.length}</span></summary><div>{charts.map(chart=><button key={chart.id} className={selectedChart?.id===chart.id?'active':''} onClick={()=>setSelectedChart(chart)}><strong>{chart.title}</strong><small>{chart.airport}</small></button>)}</div></details>)}{!faaCharts.length&&!chartBusy&&<div className="empty-cell">No terminal charts loaded for {faaAirport}. Enter a current U.S. airport ICAO code.</div>}</div></div></section><section className="card chart-viewer-card"><header><div><MapIcon size={18}/><h3>{selectedChart?.title||'Select a chart'}</h3></div>{selectedChart&&<button onClick={()=>setBinder(v=>v.some(x=>x.url===selectedChart.url)?v:[...v,{id:crypto.randomUUID(),title:selectedChart.title,airport:selectedChart.airport,url:selectedChart.url,source:'FAA d-TPP'}])}><FolderPlus size={15}/>Add to binder</button>}</header><div className="chart-viewer-body">{selectedChart?<iframe title={selectedChart.title} src={`/api/charts/pdf?url=${encodeURIComponent(selectedChart.url)}`}/>:<div className="empty-cell">Choose an airport diagram, departure, arrival, approach, or minimums page.</div>}</div></section></div>}
  {view==='binder'&&<section className="card"><header><div><Layers size={18}/><h3>Flight chart binder</h3></div></header><div className="card-body chart-binder-grid">{binder.map(i=><article key={i.id}><div><strong>{i.title}</strong><span>{i.airport} · {i.source}</span></div><button onClick={()=>setSelectedChart({id:i.id,title:i.title,airport:i.airport,type:i.source,url:i.url})}><ExternalLink size={15}/>View</button><button className="icon-button"onClick={()=>setBinder(v=>v.filter(x=>x.id!==i.id))}><Trash2 size={15}/></button></article>)}{!binder.length&&<div className="empty-cell">No charts in this binder.</div>}</div></section>}</div>
}
