import { useEffect, useMemo, useRef, useState } from 'react';
import { ExternalLink, FolderPlus, Layers, Map, Plus, Radar, Trash2 } from 'lucide-react';
import type { AnyRecord, FlightSummary } from '../lib/ofp';
import { asArray, dig } from '../lib/ofp';
import { loadLocal, saveLocal } from '../lib/storage';

declare global { interface Window { L?: any; } }
interface BinderItem { id:string; title:string; airport:string; url:string; source:string; }
function loadLeaflet(){return new Promise<any>((resolve,reject)=>{if(window.L)return resolve(window.L);if(!document.querySelector('link[data-leaflet]')){const link=document.createElement('link');link.rel='stylesheet';link.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';link.dataset.leaflet='1';document.head.appendChild(link);}const existing=document.querySelector('script[data-leaflet]') as HTMLScriptElement|null;if(existing){existing.addEventListener('load',()=>resolve(window.L));return;}const script=document.createElement('script');script.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';script.dataset.leaflet='1';script.onload=()=>resolve(window.L);script.onerror=reject;document.head.appendChild(script);});}
function RouteRadarMap({ofp,flight}:{ofp:AnyRecord|null;flight:FlightSummary}){const ref=useRef<HTMLDivElement|null>(null);const mapRef=useRef<any>(null);const [radar,setRadar]=useState(true);const points=useMemo(()=>asArray(dig(ofp,'navlog.fix','navlog.fixes')).map((f:any)=>[Number(f.pos_lat||f.latitude),Number(f.pos_long||f.longitude)]).filter((p:any)=>p.every(Number.isFinite)),[ofp]);useEffect(()=>{let disposed=false;void loadLeaflet().then(async L=>{if(disposed||!ref.current)return;if(mapRef.current){mapRef.current.remove();mapRef.current=null;}const map=L.map(ref.current,{zoomControl:true,worldCopyJump:true});mapRef.current=map;const base=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);const dark=L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:19,attribution:'© OpenStreetMap © CARTO'});const overlays:any={};if(points.length>1){const route=L.polyline(points,{weight:4,opacity:.9}).addTo(map);overlays['SimBrief route']=route;points.forEach((p:any,i:number)=>L.circleMarker(p,{radius:i===0||i===points.length-1?6:3,weight:2,fillOpacity:1}).bindTooltip(i===0?flight.origin:i===points.length-1?flight.destination:String(i+1)).addTo(map));map.fitBounds(route.getBounds(),{padding:[30,30]});}else map.setView([39,-96],4);try{const rv=await fetch('https://api.rainviewer.com/public/weather-maps.json').then(r=>r.json());const frame=rv?.radar?.past?.at(-1);if(frame){const radarLayer=L.tileLayer(`${rv.host}${frame.path}/256/{z}/{x}/{y}/2/1_1.png`,{opacity:.55,zIndex:400});overlays['Weather radar']=radarLayer;if(radar)radarLayer.addTo(map);}}catch{/* map remains useful without radar */}L.control.layers({'Street':base,'Dark':dark},overlays,{collapsed:false}).addTo(map);});return()=>{disposed=true;if(mapRef.current){mapRef.current.remove();mapRef.current=null;}}},[points,flight.origin,flight.destination,radar]);return <div ref={ref} className="route-radar-map"/>;}

export function ChartsPage({ofp,flight}:{ofp:AnyRecord|null;flight:FlightSummary;source?:any;setSource?:any}){
 const key=`aeroslate.chart-binder.${flight.origin}.${flight.destination}`;const [binder,setBinder]=useState<BinderItem[]>(()=>loadLocal(key,[]));const [title,setTitle]=useState('');const [url,setUrl]=useState('');const [view,setView]=useState<'map'|'charts'|'binder'>('map');useEffect(()=>saveLocal(key,binder),[key,binder]);const add=()=>{if(!url.trim())return;setBinder(v=>[...v,{id:crypto.randomUUID(),title:title.trim()||'Chart',airport:flight.origin,url:url.trim(),source:'Official/public chart'}]);setTitle('');setUrl('');};const chartfox=`https://chartfox.org/${flight.origin}`;const faa=`https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/dtpp/search/?ident=${encodeURIComponent(flight.origin.replace(/^K/,''))}`;
 return <div className="charts-suite"><div className="subnav-tabs"><button className={view==='map'?'active':''} onClick={()=>setView('map')}><Radar size={17}/> Route radar</button><button className={view==='charts'?'active':''} onClick={()=>setView('charts')}><Map size={17}/> Chart search</button><button className={view==='binder'?'active':''} onClick={()=>setView('binder')}><Layers size={17}/> Binder ({binder.length})</button></div>
 {view==='map'&&<section className="card map-card"><header><div><Radar size={18}/><h3>Route map & weather radar</h3></div><span className="pill blue">{flight.origin}–{flight.destination}</span></header><div className="card-body map-body"><RouteRadarMap ofp={ofp} flight={flight}/><p className="muted map-disclaimer">Interactive planning map with SimBrief route overlay and public radar tiles. Simulator use only; verify chart currency and official weather sources.</p></div></section>}
 {view==='charts'&&<div className="content-grid two"><section className="card"><header><div><Map size={18}/><h3>Worldwide chart directory</h3></div></header><div className="card-body"><p>ChartFox indexes official AIP charts for flight simulation across much of the world.</p><button className="primary" onClick={()=>window.open(chartfox,'aeroslate-chartfox')}><ExternalLink size={16}/> Open {flight.origin} charts</button></div></section><section className="card"><header><div><Map size={18}/><h3>FAA terminal procedures</h3></div></header><div className="card-body"><p>Direct official FAA d-TPP search for US airport diagrams, SIDs, STARs and approaches.</p><button onClick={()=>window.open(faa,'aeroslate-faa-charts')}><ExternalLink size={16}/> Search FAA charts</button></div></section><section className="card span-2"><header><div><FolderPlus size={18}/><h3>Add chart to binder</h3></div></header><div className="card-body binder-add-row"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Chart title, e.g. ILS 27"/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Official chart PDF or AIP URL"/><button className="primary" onClick={add}><Plus size={16}/> Add</button></div></section></div>}
 {view==='binder'&&<section className="card"><header><div><Layers size={18}/><h3>Flight chart binder</h3></div></header><div className="card-body chart-binder-grid">{binder.map(item=><article key={item.id}><div><strong>{item.title}</strong><span>{item.airport} · {item.source}</span></div><button onClick={()=>window.open(item.url,`chart-${item.id}`)}><ExternalLink size={15}/> View</button><button className="icon-button" onClick={()=>setBinder(v=>v.filter(x=>x.id!==item.id))}><Trash2 size={15}/></button></article>)}{!binder.length&&<div className="empty-cell">No charts in this flight binder. Add official chart URLs from ChartFox, FAA, or a state AIP.</div>}</div></section>}
 </div>;
}
