import { useEffect, useMemo, useState } from 'react';
import { ExternalLink, MapPin, RefreshCw, Search } from 'lucide-react';
import type { AnyRecord, FlightSummary } from '../lib/ofp';
import { dig } from '../lib/ofp';

interface Props { ofp: AnyRecord | null; flight: FlightSummary; notify: (message:string)=>void; }
interface GateResult { departureGate?:string; departureTerminal?:string; arrivalGate?:string; arrivalTerminal?:string; source?:string; updatedAt?:string; message?:string; }
export function GatePage({ofp,flight,notify}:Props){
 const [result,setResult]=useState<GateResult>({}); const [busy,setBusy]=useState(false);
 const ofpGates=useMemo(()=>({departureGate:String(dig(ofp,'origin.gate','origin.plan_gate')||''),departureTerminal:String(dig(ofp,'origin.terminal')||''),arrivalGate:String(dig(ofp,'destination.gate','destination.plan_gate')||''),arrivalTerminal:String(dig(ofp,'destination.terminal')||'')}),[ofp]);
 useEffect(()=>setResult(ofpGates),[ofpGates]);
 const lookup=async()=>{setBusy(true);try{const q=new URLSearchParams({flight:`${flight.airline}${flight.flightNumber}`,origin:flight.origin,destination:flight.destination,date:flight.flightDate});const r=await fetch(`/api/gates?${q}`);const data=await r.json();if(!r.ok)throw new Error(data.error||'Gate lookup unavailable.');setResult({...ofpGates,...data});notify(data.message||'Gate data refreshed.');}catch(e){notify(e instanceof Error?e.message:'Gate lookup failed.');}finally{setBusy(false);}};
 const fr24=`https://www.flightradar24.com/data/flights/${(`${flight.airline}${flight.flightNumber}`).toLowerCase()}`;
 return <div className="gate-page content-grid two"><section className="card span-2"><header><div><MapPin size={18}/><h3>Departure & arrival gates</h3></div><button className="primary" onClick={()=>void lookup()} disabled={busy}><RefreshCw size={16} className={busy?'spin':''}/>{busy?'Checking…':'Refresh live data'}</button></header><div className="card-body gate-summary-grid"><div><span>{flight.origin} departure</span><strong>{result.departureTerminal?`Terminal ${result.departureTerminal} · `:''}{result.departureGate||'Gate not published'}</strong></div><div><span>{flight.destination} arrival</span><strong>{result.arrivalTerminal?`Terminal ${result.arrivalTerminal} · `:''}{result.arrivalGate||'Gate not published'}</strong></div></div></section><section className="card"><header><div><Search size={18}/><h3>Current flight</h3></div></header><div className="card-body status-list"><div><span>Flight</span><strong>{flight.airline}{flight.flightNumber}</strong></div><div><span>Route</span><strong>{flight.origin} → {flight.destination}</strong></div><div><span>Source</span><strong>{result.source||'SimBrief / live provider adapter'}</strong></div><div><span>Updated</span><strong>{result.updatedAt||'—'}</strong></div></div></section><section className="card"><header><div><ExternalLink size={18}/><h3>Live source</h3></div></header><div className="card-body"><p className="muted">Gate assignments change frequently. AeroSlate uses any gate data included in the OFP first, then an optional live provider configured on the Render service.</p><button onClick={()=>window.open(fr24,'aeroslate-flight-status')}><ExternalLink size={16}/> Open current flight status</button></div></section></div>;
}
