import { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronDown, ChevronRight, CloudUpload, Plane, Save, Send, Shuffle, Trash2 } from 'lucide-react';
import airportCatalog from '../data/airports.catalog.json';
import { buildSimbriefDispatch, generateDispatchPayload, type Airport, type FlightCandidate } from '../lib/dispatchlink';
import { loadLocal, saveLocal } from '../lib/storage';
import { appendLedgerRecord, emptyLedger, getOrCreateDeviceId, normalizeLedger, synchronizeLedger, type AeroSlateLedger, type GitHubCloudConfig, type LedgerEntry, type RecordData } from '../lib/cloudLedger';
interface Props{candidate:FlightCandidate|null;onDispatch:(url:string,flight:FlightCandidate,staticId:string)=>void;notify:(message:string)=>void}
interface CloudPrefs{gistId:string;token:string;passphrase:string;autoSync:boolean;rememberSecrets:boolean}
const LEDGER_KEY='aeroslate.records.ledger.v2', CLOUD_KEY='aeroslate.records.github.v1';
const AIRPORTS=(airportCatalog as Airport[]).filter(a=>a.icao&&a.size!=='small');
function tripFlight(d:RecordData):FlightCandidate{return{id:String(d.candidateId),date:String(d.date),aircraft:String(d.aircraft),registration:String(d.registration),flightNumber:String(d.flightNumber),departure:String(d.departure),arrival:String(d.arrival),std:String(d.std),sta:String(d.sta),ete:String(d.ete),rawStd:String(d.rawStd||''),rawSta:String(d.rawSta||'')}}
function isoDate(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseDate(value:string){const d=new Date(`${String(value).slice(0,10)}T12:00:00`);return Number.isNaN(d.getTime())?new Date():d}
function zuluMinutes(value:string){const m=String(value).match(/(\d{1,2}):(\d{2})/);return m?(Number(m[1])*60+Number(m[2]))%1440:0}
function clock(minutes:number){const m=((Math.round(minutes)%1440)+1440)%1440;return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}z`}
function durationText(minutes:number){return `${Math.floor(minutes/60)}:${String(minutes%60).padStart(2,'0')}`}
function sameTrip(entry:LedgerEntry,f:FlightCandidate,date:string){return String(entry.data.candidateId)===f.id&&String(entry.data.date).slice(0,10)===date}
export function TripsPage({candidate,onDispatch,notify}:Props){
 const readLedger=useCallback(()=>normalizeLedger(loadLocal(LEDGER_KEY,emptyLedger())),[]);
 const [ledger,setLedger]=useState<AeroSlateLedger>(readLedger);const [busy,setBusy]=useState(false);const [month,setMonth]=useState(()=>candidate?parseDate(candidate.date):new Date());const [selectedDate,setSelectedDate]=useState(()=>candidate?String(candidate.date).slice(0,10):isoDate(new Date()));const [legs,setLegs]=useState(3);const deviceId=useMemo(()=>getOrCreateDeviceId(),[]);const stored=loadLocal<Partial<CloudPrefs>>(CLOUD_KEY,{});const cloud:CloudPrefs={gistId:stored.gistId||'',token:stored.rememberSecrets?stored.token||'':'',passphrase:stored.rememberSecrets?stored.passphrase||'':'',autoSync:stored.autoSync??true,rememberSecrets:stored.rememberSecrets??false};
 useEffect(()=>{const refresh=()=>setLedger(readLedger());window.addEventListener('aeroslate-ledger-updated',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('aeroslate-ledger-updated',refresh);window.removeEventListener('storage',refresh)}},[readLedger]);
 useEffect(()=>{if(candidate?.date){const d=parseDate(candidate.date);setSelectedDate(isoDate(d));setMonth(new Date(d.getFullYear(),d.getMonth(),1));}},[candidate?.id]);
 const commit=(next:AeroSlateLedger)=>{setLedger(next);saveLocal(LEDGER_KEY,next);window.dispatchEvent(new CustomEvent('aeroslate-ledger-updated'));};
 const saveCandidates=async(list:FlightCandidate[],rigId='')=>{let next=readLedger();let saved=0;for(const f of list){const date=String(f.date||selectedDate).slice(0,10);if(next.trips.some(e=>sameTrip(e,f,date)))continue;const load=generateDispatchPayload(f);const data:RecordData={candidateId:f.id,date,flightNumber:f.flightNumber,departure:f.departure,arrival:f.arrival,aircraft:f.aircraft,registration:f.registration,std:f.std,sta:f.sta,ete:f.ete,rawStd:f.rawStd||'',rawSta:f.rawSta||'',status:'Scheduled',rigId,...load};next=(await appendLedgerRecord(next,'trip',data,deviceId)).ledger;saved++;}commit(next);notify(saved?`${saved}-leg trip added to ${selectedDate}.`:'Those legs are already on the itinerary.');};
 const addTrip=()=>candidate?void saveCandidates([{...candidate,date:selectedDate}]):notify('Select a parsed flight in Flight Finder first.');
 const generateRig=()=>{const flights=loadLocal<FlightCandidate[]>('aeroslate.finder.flights',[]);if(!candidate&&!flights.length)return notify('Paste flights in Flight Finder first.');let current={...(candidate||flights[Math.floor(Math.random()*flights.length)]),date:selectedDate};const result=[current];const count=Math.min(5,Math.max(1,legs));for(let i=1;i<count;i++){const real=flights.filter(f=>f.departure===current.arrival&&!result.some(x=>x.id===f.id));if(real.length){current={...real[Math.floor(Math.random()*real.length)],date:selectedDate};result.push(current);continue;}const options=AIRPORTS.filter(a=>a.icao!==current.arrival&&a.icao!==current.departure);const destination=options[Math.floor(Math.random()*options.length)]?.icao||current.departure;const turn=45+Math.floor(Math.random()*46),leg=55+Math.floor(Math.random()*166),std=zuluMinutes(current.sta||current.std)+turn,sta=std+leg;current={...current,id:`rig-${crypto.randomUUID()}`,departure:current.arrival,arrival:destination,std:clock(std),sta:clock(sta),ete:durationText(leg),rawStd:clock(std),rawSta:clock(sta),date:selectedDate};result.push(current);}void saveCandidates(result,crypto.randomUUID());};
 const removeTrip=(id:string)=>{const next={...readLedger(),trips:readLedger().trips.filter(e=>e.id!==id),updatedAt:new Date().toISOString()};commit(next);notify('Trip removed from this device. Sync Gist to update the cloud copy.');};
 const sync=async()=>{if(!cloud.token||cloud.passphrase.length<12)return notify('Configure GitHub Gist sync in Flight Logs first.');try{setBusy(true);const r=await synchronizeLedger({token:cloud.token,gistId:cloud.gistId,passphrase:cloud.passphrase} as GitHubCloudConfig,readLedger());commit(r.ledger);saveLocal(CLOUD_KEY,{...stored,gistId:r.gistId});notify('Trip calendar synchronized.');}catch(e){notify(e instanceof Error?e.message:'Sync failed.')}finally{setBusy(false)}};
 const trips=ledger.trips.slice().sort((a,b)=>`${a.data.date} ${a.data.std}`.localeCompare(`${b.data.date} ${b.data.std}`));const year=month.getFullYear(),m=month.getMonth();const first=new Date(year,m,1),days=new Date(year,m+1,0).getDate(),start=first.getDay();const cells=Array.from({length:Math.ceil((start+days)/7)*7},(_,i)=>{const day=i-start+1;return day>0&&day<=days?new Date(year,m,day):null});
 const dispatch=(entry:LedgerEntry)=>{const f=tripFlight(entry.data),p=buildSimbriefDispatch(f,{pax:Number(entry.data.pax),cargo:Number(entry.data.freight),remarks:`AeroSlate scheduled load: ${entry.data.bags} bags.`});onDispatch(p.url,f,p.staticId)};
 return <div className="trips-page"><section className="card trip-scheduler"><header><div><CalendarDays size={18}/><h3>Trip builder</h3></div><button onClick={()=>void sync()} disabled={busy}><CloudUpload size={16}/>{busy?'Syncing…':'Sync Gist'}</button></header><div className="card-body trip-builder-grid"><div><strong>{candidate?`${candidate.flightNumber} · ${candidate.departure}–${candidate.arrival}`:'No selected flight'}</strong><span>{candidate?`${selectedDate} · ${candidate.std}–${candidate.sta}`:'Select a flight in Flight Finder.'}</span><label className="trip-date-picker"><span>Schedule date</span><input type="date" value={selectedDate} onChange={e=>{setSelectedDate(e.target.value);const d=parseDate(e.target.value);setMonth(new Date(d.getFullYear(),d.getMonth(),1));}}/></label><button className="primary" onClick={addTrip} disabled={!candidate}><Save size={16}/> Add single leg</button></div><div className="rig-builder"><label><span>Rig length</span><select value={legs} onChange={e=>setLegs(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} leg{n===1?'':'s'}</option>)}</select></label><button onClick={generateRig}><Shuffle size={16}/> Generate connected rig</button></div></div></section>
 <section className="card planner-card"><header><div><CalendarDays size={18}/><h3>{month.toLocaleString(undefined,{month:'long',year:'numeric'})}</h3></div><div><button className="icon-button" onClick={()=>setMonth(new Date(year,m-1,1))}><ChevronDown style={{transform:'rotate(90deg)'}}/></button><button className="icon-button" onClick={()=>setMonth(new Date(year,m+1,1))}><ChevronRight/></button></div></header><div className="card-body planner-grid">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><b key={d}>{d}</b>)}{cells.map((d,i)=>{const date=d?isoDate(d):'';return <div role={d?'button':undefined} tabIndex={d?0:-1} className={`planner-day ${!d?'blank':''} ${date===selectedDate?'selected':''}`} key={i} onClick={()=>d&&setSelectedDate(date)} onKeyDown={e=>{if(d&&(e.key==='Enter'||e.key===' '))setSelectedDate(date)}}>{d&&<><span>{d.getDate()}</span>{trips.filter(t=>String(t.data.date).slice(0,10)===date).map(t=><article key={t.id} onClick={e=>e.stopPropagation()}><strong>{String(t.data.flightNumber)}</strong><small>{String(t.data.departure)}–{String(t.data.arrival)}</small><button title="Dispatch" onClick={()=>dispatch(t)}><Send size={11}/></button></article>)}</>}</div>})}</div></section>
 <section className="card"><header><div><Plane size={18}/><h3>Itinerary</h3></div><span className="pill neutral">{trips.length}</span></header><div className="card-body trip-list">{trips.map(e=><article key={e.id}><div className="trip-date"><strong>{String(e.data.date)}</strong><span>{String(e.data.std)}–{String(e.data.sta)}</span></div><div className="trip-route"><strong>{String(e.data.flightNumber)} · {String(e.data.departure)} → {String(e.data.arrival)}</strong><span>{String(e.data.aircraft)} · {String(e.data.registration)}</span></div><div className="trip-load"><strong>{String(e.data.pax)} pax</strong><span>{String(e.data.bags)} bags · {Number(e.data.freight||0).toLocaleString()} lb freight</span></div><div className="trip-actions"><button className="primary compact" onClick={()=>dispatch(e)}><Send size={14}/> Dispatch</button><button className="compact danger-button" onClick={()=>removeTrip(e.id)}><Trash2 size={14}/> Remove</button></div></article>)}{!trips.length&&<div className="empty-cell">No trips scheduled. Select a flight, choose a date, and add it above.</div>}</div></section></div>;
}
